name       : alglib
version    : 3.18.0
release    : 2
source     :
    - http://www.alglib.net/translator/re/alglib-3.18.0.cpp.gpl.tgz : 98ee704574321f10b25fdab64549c114c00df9629092b971cce9fedfd96ee829
license    : GPL-2.0-or-later
component  : programming.library
summary    : A numerical analysis and data processing library (free edition)
description: |
    ALGLIB is a cross-platform numerical analysis and data processing library.

    ALGLIB features include:
    * Data analysis (classification/regression, statistics)
    * Optimization and nonlinear solvers
    * Interpolation and linear/nonlinear least-squares fitting
    * Linear algebra (direct algorithms, EVD/SVD), direct and iterative linear solvers
    * Fast Fourier Transform and many other algorithms
patterns   : /usr
setup      : |
    # Borrowed from Fedora
    cp $pkgfiles/CMakeLists.txt .

    %cmake  . -DALGLIB_VERSION=${version} -DLIB_SUFFIX="%LIBSUFFIX%"
build      : |
    %make
install    : |
    %make_install
    ln -s %libdir%/libalglib-${version}.so $installdir/%libdir%/libalglib.so
check      : |
    ./test_c
